### ISSUE TITLE
The model is not trained in incremenal session ?

### ISSUE THREAD

**Issue by jjunsss** [JungHunOh/CLOSER_ECCV2024#2]
## Question about Model Adaptation in fscil_trainer.py
First of all, Thank you for your insightful work on FSCIL domain!

### Question.
I have questions about the model training process in `fscil_trainer.py` (lines 107-128):

1. What is the model's frozen status in this section?
2. After calling `self.model.eval()`, how does the model adapt to the new dataset?

Thank you for your help!

**Comment by JungHunOh** [comment]
Hi, thanks for your interest in our work.

Our work aims to develop a representation learning method during the **base session** without adapting during incremental sessions.
This is because adapting few-shot and incremental data is too challenging to avoid overfitting and catastrophic forgetting problems.
Without adapting to new classes, the representation acquired through our method can exhibit good transferability to new classes.

Thus,
1. All model parameters are frozen and we only append new class prototypes to the classifier.
2. There is no adaptation process.

**Comment by jjunsss** [comment]
I appreciate your detailed explanation.
I understand it!
